name = "core-builds-cors-proxy"
main = "worker.js"
compatibility_date = "2026-01-01"

[observability]
enabled = false

[[kv_namespaces]]
binding = "TEMPLATES"
id = "100cc344297b41c785f8c07dba85982c"

[[kv_namespaces]]
binding = "STATS"
id = "e21df08fe77846ee8246bda94288c111"
