// Parser-safe AIOStreams formatter conditions for AIO Enhanced mode.
//
// AIOStreams' formatter `~` operator is a case-insensitive substring check for strings and
// an exact, case-insensitive membership check for string arrays. It is not regular-expression
// syntax. Keeping these canonical parsed values separate from the Universal filename regexes
// prevents formatter grammar characters from leaking into generated templates.
export const MARKER_TERMS = Object.freeze({
  'res-4k':            { mode:'exact', values:['2160p'] },
  'res-1440p':         { mode:'exact', values:['1440p'] },
  'res-1080p':         { mode:'exact', values:['1080p'] },
  'res-720p':          { mode:'exact', values:['720p'] },
  'res-576p':          { mode:'exact', values:['576p'] },
  'res-480p':          { mode:'exact', values:['480p'] },
  'res-360p':          { mode:'exact', values:['360p'] },
  'res-240p':          { mode:'exact', values:['240p'] },
  'res-144p':          { mode:'exact', values:['144p'] },

  'src-remux':         { mode:'exact', values:['Bluray REMUX','BluRay REMUX'] },
  'src-bluray':        { mode:'exact', values:['Bluray','BluRay'] },
  'src-webdl':         { mode:'exact', values:['WEB-DL'] },
  'src-webrip':        { mode:'exact', values:['WEBRip'] },
  'src-hdtv':          { mode:'exact', values:['HDTV'] },
  'src-hdrip':         { mode:'exact', values:['HDRip'] },
  'src-dvdrip':        { mode:'exact', values:['DVDRip'] },
  'src-dvd':           { mode:'exact', values:['DVD'] },
  'src-cam':           { mode:'exact', values:['CAM','HDCAM','CAMRip'] },
  'src-ts':            { mode:'exact', values:['TS','Telesync','HDTS'] },

  'vis-dv':            { mode:'contains', values:['DV','Dolby Vision'] },
  'vis-hdr10plus':     { mode:'contains', values:['HDR10+'] },
  'vis-hdr10':         { mode:'contains', values:['HDR10'] },
  'vis-hdr':           { mode:'contains', values:['HDR'] },
  'vis-hlg':           { mode:'contains', values:['HLG'] },
  'vis-sdr':           { mode:'contains', values:['SDR','STANDARD'] },
  'vis-10bit':         { mode:'contains', values:['10BIT','10bit'] },
  'vis-imax-enhanced': { mode:'contains', values:['IMAX Enhanced'] },
  'vis-imax':          { mode:'contains', values:['IMAX'] },
  'vis-3d':            { mode:'contains', values:['3D','SBS','TAB'] },

  'aud-atmos':         { mode:'contains', values:['Atmos','ATMOS'] },
  'aud-truehd':        { mode:'contains', values:['TrueHD','TRUEHD'] },
  'aud-ddplus':        { mode:'contains', values:['DD+','DDP','EAC3'] },
  'aud-dd':            { mode:'contains', values:['DD','AC3'] },
  'aud-dtsx':          { mode:'contains', values:['DTS:X','DTS-X'] },
  'aud-dtshdma':       { mode:'contains', values:['DTS-HD MA'] },
  'aud-dtshd':         { mode:'contains', values:['DTS-HD'] },
  'aud-dts':           { mode:'contains', values:['DTS'] },
  'aud-flac':          { mode:'contains', values:['FLAC'] },
  'aud-pcm':           { mode:'contains', values:['PCM','LPCM'] },
  'aud-opus':          { mode:'contains', values:['Opus','OPUS'] },
  'aud-aac':           { mode:'contains', values:['AAC'] },
  'aud-mp3':           { mode:'contains', values:['MP3'] },
  'aud-vorbis':        { mode:'contains', values:['Vorbis','VORBIS'] },

  'ch-71':             { mode:'contains', values:['7.1'] },
  'ch-61':             { mode:'contains', values:['6.1'] },
  'ch-51':             { mode:'contains', values:['5.1'] },
  'ch-20':             { mode:'contains', values:['2.0','Stereo'] },
  'ch-10':             { mode:'contains', values:['1.0','Mono'] },

  'codec-av1':         { mode:'exact', values:['AV1'] },
  'codec-hevc':        { mode:'exact', values:['HEVC','H265','x265'] },
  'codec-avc':         { mode:'exact', values:['AVC','H264','x264'] },
  'codec-vc1':         { mode:'exact', values:['VC-1','VC1'] },
  'codec-xvid':        { mode:'exact', values:['XviD'] },
  'codec-divx':        { mode:'exact', values:['DivX'] },

  'status-p2p':        { mode:'exact', values:['p2p'] },

  'tier-remux-t1':     { mode:'contains', values:['Remux T1','UHD Remux T1'] },
  'tier-remux-t2':     { mode:'contains', values:['Remux T2','UHD Remux T2'] },
  'tier-bluray-t1':    { mode:'contains', values:['Bluray T1','BluRay T1','UHD Bluray T1','HD Bluray T1'] },
  'tier-bluray-t2':    { mode:'contains', values:['Bluray T2','BluRay T2','UHD Bluray T2','HD Bluray T2'] },
  'tier-web-t1':       { mode:'contains', values:['Web T1','WEB T1'] },
  'tier-web-t2':       { mode:'contains', values:['Web T2','WEB T2'] },
  'tier-penalty':      { mode:'contains', values:['Bad','Penalty','Low Quality'] },

  'trust-premier':     { mode:'exact', values:['FraMeSToR','EPSiLON','FLUX','NTb','QxR','Tigole','D-Z0N3','HiFi','DON','HUNO','BMF'] },

  'edition-director':  { mode:'contains', values:["Director's Cut",'Directors Cut','DIR CUT'] },
  'edition-extended':  { mode:'contains', values:['Extended','Extended Cut','Extended Edition'] },
  'edition-theatrical':{ mode:'contains', values:['Theatrical','Theatrical Cut'] },
  'edition-criterion': { mode:'contains', values:['Criterion'] },
  'edition-open-matte':{ mode:'contains', values:['Open Matte'] },
  'edition-hybrid':    { mode:'contains', values:['Hybrid'] },
  'edition-blackwhite':{ mode:'contains', values:['Black & White','Authentic BW'] },

  'net-netflix':       { mode:'contains', values:['Netflix'] },
  'net-prime':         { mode:'contains', values:['Amazon','Prime Video'] },
  'net-apple':         { mode:'contains', values:['Apple TV','iTunes'] },
  'net-disney':        { mode:'contains', values:['Disney'] },
  'net-max':           { mode:'contains', values:['HBO Max','Max'] },
  'net-hulu':          { mode:'contains', values:['Hulu'] },
  'net-peacock':       { mode:'contains', values:['Peacock'] },
  'net-paramount':     { mode:'contains', values:['Paramount'] },
  'net-crunchyroll':   { mode:'contains', values:['Crunchyroll'] },

  'lang-en':           { mode:'contains', values:['English','eng'] },
  'lang-es':           { mode:'contains', values:['Spanish','spa'] },
  'lang-fr':           { mode:'contains', values:['French','fre','fra'] },
  'lang-de':           { mode:'contains', values:['German','ger','deu'] },
  'lang-it':           { mode:'contains', values:['Italian','ita'] },
  'lang-pt':           { mode:'contains', values:['Portuguese','por'] },
  'lang-ja':           { mode:'contains', values:['Japanese','jpn'] },
  'lang-ko':           { mode:'contains', values:['Korean','kor'] },
  'lang-multi':        { mode:'contains', values:['Multi','Dual Audio'] },

  'sub-en':            { mode:'contains', values:['🇬🇧','🇺🇸'] },
  'sub-es':            { mode:'contains', values:['🇪🇸'] },
  'sub-fr':            { mode:'contains', values:['🇫🇷'] },
  'sub-de':            { mode:'contains', values:['🇩🇪'] },
  'sub-it':            { mode:'contains', values:['🇮🇹'] },
  'sub-pt':            { mode:'contains', values:['🇵🇹','🇧🇷'] },
  'sub-ja':            { mode:'contains', values:['🇯🇵'] },
  'sub-ko':            { mode:'contains', values:['🇰🇷'] },
});
